import { Poppins } from 'next/font/google';
import { Josefin_Sans } from 'next/font/google';
import { ThemeProvider } from "./utils/theme.provider";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Poppins", // Corrected the variable name
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Josefin", // Corrected the variable name
});


// export const metadata: Metadata = {
//   title: "SUNAM IT CENTER",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${josefin.variable} !bg-white  antialiased`} 
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
